// Generated by CoffeeScript 1.6.2
var parse, scripts, templateParser;

templateParser = require("./template/parser");

exports.parse = parse = function(content, options) {
  if (options == null) {
    options = {};
  }
  content = templateParser.parse(content);
  return String(content);
};

exports.compile = function(content) {
  var module;

  module = {
    exports: {}
  };
  eval(parse(content));
  return module.exports;
};

scripts = {};

exports.script = function(name) {
  var _ref;

  return (_ref = scripts[name]) != null ? _ref : (scripts[name] = exports.compile($("script[data-template-name='" + name + "']").html()));
};

if (typeof (typeof window !== "undefined" && window !== null ? window.paperclip : void 0) !== "undefined") {
  window.paperclip.compile = exports.compile;
  window.paperclip.script = exports.script;
}
