// Generated by CoffeeScript 1.6.2
var formatter, templateParser;

templateParser = require("./template/parser");

formatter = require("./template/formatter");

exports.parse = function(content, options) {
  if (options == null) {
    options = {};
  }
  content = templateParser.parse(content);
  return formatter.format(content);
};
