// Generated by CoffeeScript 1.7.0
(function() {
  var blockBindings, name, pc;

  pc = require("../browser");

  blockBindings = require("./paper/bindings/block");

  for (name in blockBindings) {
    pc.blockBinding(name, blockBindings[name]);
  }

}).call(this);
