// Generated by CoffeeScript 1.6.2
var NodeExpression,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

NodeExpression = (function(_super) {
  __extends(NodeExpression, _super);

  NodeExpression.prototype._type = "node";

  /*
  */


  function NodeExpression(name, attributes, children) {
    this.name = name;
    this.attributes = attributes;
    this.children = children;
    NodeExpression.__super__.constructor.call(this);
    this.addChild.apply(this, this.attributes);
    this.addChild.apply(this, this.children);
  }

  /*
  */


  NodeExpression.prototype.toString = function() {
    var buffer;

    buffer = ["this.node('" + this.name + "')"];
    if (this.attributes.length) {
      buffer.push(this.attributes.join("."));
    }
    if (this.children.length) {
      buffer.push("children(" + (this.children.join(",")) + ")");
    }
    return buffer.join(".");
  };

  return NodeExpression;

})(require("./base"));

module.exports = NodeExpression;
