// Generated by CoffeeScript 1.6.2
var TextExpression,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TextExpression = (function(_super) {
  __extends(TextExpression, _super);

  TextExpression.prototype._type = "text";

  /*
  */


  function TextExpression(items) {
    TextExpression.__super__.constructor.call(this, items);
  }

  /*
  */


  TextExpression.prototype.toString = function() {
    return ["this.text()"].concat(this.items).join(".");
  };

  return TextExpression;

})(require("./collection"));

module.exports = TextExpression;
