// Generated by CoffeeScript 1.6.2
var BindDecorator, DecoratorFactory, ElementDecorator, TextDecorator;

TextDecorator = require("./text");

ElementDecorator = require("./element");

BindDecorator = require("./bind");

DecoratorFactory = (function() {
  function DecoratorFactory() {}

  /*
  */


  DecoratorFactory.prototype.attach = function(data, element) {
    var classes;

    classes = [];
    if (element.nodeName === "#text") {
      if (TextDecorator.test(element)) {
        classes.push(TextDecorator);
      }
    } else {
      if (ElementDecorator.test(element)) {
        classes.push(ElementDecorator);
      } else if (BindDecorator.test(element)) {
        classes.push(BindDecorator);
      }
    }
    if (!classes.length) {
      return;
    }
    return element._pcDecorators = classes.map(function(clazz) {
      return new clazz(data, element);
    });
  };

  return DecoratorFactory;

})();

module.exports = DecoratorFactory;
