// Generated by CoffeeScript 1.6.2
(function() {
  var ScriptBinding,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ScriptBinding = (function(_super) {
    __extends(ScriptBinding, _super);

    /*
    */


    function ScriptBinding(clip, scriptName) {
      this.clip = clip;
      this.scriptName = scriptName;
      this.script = clip.script(this.scriptName);
    }

    /*
    */


    ScriptBinding.prototype.bind = function(context) {
      var self;

      this.context = context;
      if (this.watch !== false) {
        this.script.watch().update();
      }
      self = this;
      this._binding = this.clip.bind(this.scriptName, function(value) {
        return self._onChange(value);
      }).now();
      return this;
    };

    /*
    */


    ScriptBinding.prototype.unbind = function() {
      var _ref;

      if ((_ref = this._binding) != null) {
        _ref.dispose();
      }
      this._binding = void 0;
      return this;
    };

    /*
    */


    ScriptBinding.prototype._onChange = function(value) {};

    return ScriptBinding;

  })(require("./index"));

  module.exports = ScriptBinding;

}).call(this);
