// Generated by CoffeeScript 1.6.2
var Base, async, pilot;

async = require("async");

pilot = require("pilot-block");

Base = (function() {
  /*
  */
  Base.prototype.__isNode = true;

  /*
  */


  function Base() {
    this.children = [];
  }

  /*
  */


  Base.prototype.bind = function() {
    var child, _i, _len, _ref;

    _ref = this.children || [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      child.bind();
    }
    return this;
  };

  /*
  */


  Base.prototype.dispose = function() {
    return this.section.dispose();
  };

  /*
  */


  Base.prototype.attach = function(element, context, callback) {
    var _this = this;

    if (callback == null) {
      callback = (function() {});
    }
    return this.load(context.detachBuffer(), function(err) {
      if (err != null) {
        return callback(err);
      }
      if (element.__isNode) {
        element.section.append(pilot.createSection(context.buffer.join("")));
        pilot.update(element.section.parent);
      } else {
        element.innerHTML = context.buffer.join("");
        pilot.update(element);
      }
      _this.bind();
      return callback();
    });
  };

  /*
   writes HTML to the DOM
  */


  Base.prototype.load = function(context, callback) {
    var _this = this;

    this.context = context;
    this._writeHead(context, function(err) {
      if (err != null) {
        return callback(err);
      }
      return _this._loadChildren(context, function(err) {
        if (err != null) {
          return callback(err);
        }
        return _this._writeTail(context, function(err) {
          return callback(err, context);
        });
      });
    });
    return this;
  };

  /*
  */


  Base.prototype._writeHead = function(info, callback) {
    return callback();
  };

  /*
  */


  Base.prototype._loadChildren = function(info, callback) {
    return Base.loadEachItem(this.children || [], info, callback);
  };

  /*
  */


  Base.prototype._writeTail = function(info, callback) {
    return callback();
  };

  /*
  */


  Base.prototype.addChild = function() {
    var child, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      child = arguments[_i];
      child.parent = this;
      _results.push(this.children.push(child));
    }
    return _results;
  };

  /*
  */


  Base.loadEachItem = function(source, info, callback) {
    return async.eachSeries(source, (function(child, next) {
      return child.load(info, next);
    }), callback);
  };

  /*
   used mostly for block bindings
  */


  Base.cloneEach = function(source) {
    var item, items, _i, _len;

    items = [];
    for (_i = 0, _len = source.length; _i < _len; _i++) {
      item = source[_i];
      items.push(item.clone());
    }
    return items;
  };

  return Base;

})();

module.exports = Base;
