// Generated by CoffeeScript 1.7.0
(function() {
  var GroupExpresion, ParamsExpression,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ParamsExpression = require("./params");

  GroupExpresion = (function(_super) {
    __extends(GroupExpresion, _super);

    function GroupExpresion() {
      return GroupExpresion.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    GroupExpresion.prototype._type = "group";


    /*
     */

    GroupExpresion.prototype.toString = function() {
      return "(" + (GroupExpresion.__super__.toString.call(this)) + ")";
    };

    return GroupExpresion;

  })(ParamsExpression);

  module.exports = GroupExpresion;

}).call(this);
