// Generated by CoffeeScript 1.7.0
(function() {
  var JSExpression, base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  base = require("../../base/expression");

  JSExpression = (function(_super) {
    __extends(JSExpression, _super);


    /*
     */

    JSExpression.prototype._type = "js";


    /*
     */

    function JSExpression(value) {
      this.value = value;
      JSExpression.__super__.constructor.call(this);
    }


    /*
     */

    JSExpression.prototype.toString = function() {
      return this.value;
    };

    return JSExpression;

  })(base.Expression);

  module.exports = JSExpression;

}).call(this);
