// Generated by CoffeeScript 1.7.0
(function() {
  var OptionsExpression, base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  base = require("../../base/expression");

  OptionsExpression = (function(_super) {
    __extends(OptionsExpression, _super);


    /*
     */

    OptionsExpression.prototype._type = "options";


    /*
     */

    function OptionsExpression(items) {
      this.items = items;
      OptionsExpression.__super__.constructor.call(this);
      this.addChild.apply(this, items);
    }

    OptionsExpression.prototype.toString = function() {
      return "{" + (this.items.join(",")) + "}";
    };

    return OptionsExpression;

  })(base.Expression);

  module.exports = OptionsExpression;

}).call(this);
