// Generated by CoffeeScript 1.7.0
(function() {
  var CollectionExpression, ParamsExpression,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionExpression = require("../../base/collectionExpression");

  ParamsExpression = (function(_super) {
    __extends(ParamsExpression, _super);

    function ParamsExpression() {
      return ParamsExpression.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    ParamsExpression.prototype._type = "params";


    /*
     */

    ParamsExpression.prototype.toString = function() {
      return this.items.map(function(item) {
        return item.toString();
      }).join(",");
    };

    return ParamsExpression;

  })(CollectionExpression);

  module.exports = ParamsExpression;

}).call(this);
