// Generated by CoffeeScript 1.7.0
(function() {
  var RefExpression;

  RefExpression = (function() {

    /*
     */
    RefExpression.prototype._type = "ref";


    /*
     */

    function RefExpression(name, unbound) {
      this.unbound = unbound;
      this._children = [];
      if (name.substr(0, 1) === "@") {
        this.self = true;
        this.name = name.substr(1);
      } else {
        this.name = name;
      }
    }


    /*
     */

    RefExpression.prototype.toString = function() {
      return this.name;
    };

    return RefExpression;

  })();

  module.exports = RefExpression;

}).call(this);
