// Generated by CoffeeScript 1.7.0
(function() {
  var BlockBinding,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BlockBinding = (function(_super) {
    __extends(BlockBinding, _super);


    /*
     */

    function BlockBinding(options) {
      var clip;
      clip = options.clip;
      this.section = options.section;
      this.application = options.application;
      this.nodeFactory = this.application.nodeFactory;
      this.contentTemplate = options.template;
      this.scriptName = options.scriptName;
      this.childBlockTemplate = options.childBlockTemplate;
      this.script = clip.script(this.scriptName);
      BlockBinding.__super__.constructor.call(this, this.application, clip, this.scriptName);
    }


    /*
     */

    BlockBinding.prototype.bind = function(context) {
      this.context = context;
      this.clip.reset(this.context, false);
      return BlockBinding.__super__.bind.call(this, this.context);
    };

    BlockBinding.prototype.unbind = function() {
      BlockBinding.__super__.unbind.call(this);
      return this.clip.unwatch();
    };


    /*
     */

    BlockBinding.test = function(node) {
      return false;
    };

    return BlockBinding;

  })(require("../base/script"));

  module.exports = BlockBinding;

}).call(this);
