// Generated by CoffeeScript 1.7.0

/*

{{#when:condition}}
  do something
{{/}}
 */

(function() {
  var BlockDecor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BlockDecor = (function(_super) {
    __extends(BlockDecor, _super);

    function BlockDecor() {
      return BlockDecor.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    BlockDecor.prototype._onChange = function(value, oldValue) {
      var child, childTemplate, _ref;
      child = this.child;
      if ((_ref = this.child) != null) {
        _ref.unbind();
      }
      this.child = void 0;
      if (value) {
        childTemplate = this.contentTemplate;
      } else {
        childTemplate = this.childBlockTemplate;
      }
      if (childTemplate) {
        this.child = childTemplate.bind(this.context);
        return this.section.replaceChildNodes(this.child.render());
      } else if (child != null) {
        return child.dispose();
      }
    };


    /*
     */

    BlockDecor.prototype.unbind = function() {
      var _ref;
      BlockDecor.__super__.unbind.call(this);
      return (_ref = this.child) != null ? _ref.dispose() : void 0;
    };

    return BlockDecor;

  })(require("./base"));

  module.exports = BlockDecor;

}).call(this);
