// Generated by CoffeeScript 1.6.2
var BindingCollection, Factory, bindingClasses;

BindingCollection = require("../collection");

bindingClasses = {
  html: require("./html"),
  "if": require("./conditional"),
  "else": require("./conditional"),
  elseif: require("./conditional"),
  value: require("./value")
};

Factory = (function() {
  function Factory() {}

  /*
  */


  Factory.prototype.getBindings = function(options) {
    var bd, bindings, clipScriptNames, scriptName, _i, _len;

    bindings = [];
    clipScriptNames = options.clip.scripts.names;
    for (_i = 0, _len = clipScriptNames.length; _i < _len; _i++) {
      scriptName = clipScriptNames[_i];
      if (bd = bindingClasses[scriptName]) {
        options.scriptName = scriptName;
        bindings.push(new bd(options));
      }
    }
    return bindings;
  };

  /*
  */


  Factory.prototype.register = function(name, bindingClass) {
    return bindingClasses[name] = bindingClass;
  };

  return Factory;

})();

module.exports = new Factory();
