// Generated by CoffeeScript 1.6.2
var HtmlDecor, type, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

type = require("type-component");

HtmlDecor = (function(_super) {
  __extends(HtmlDecor, _super);

  function HtmlDecor() {
    _ref = HtmlDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  HtmlDecor.prototype._onChange = function(value) {
    var dom, node, _ref1;

    if (!value) {
      return this.section.removeChildNodes();
    }
    if (value.__isLoader) {
      node = value.node;
    } else if (value.nodeType != null) {
      node = value;
    } else {
      if (typeof window === "undefined") {
        node = this.nodeFactory.createTextNode(String(value));
      } else {
        dom = this.nodeFactory.createElement("div");
        dom.innerHTML = String(value);
        node = (_ref1 = this.nodeFactory).createFragment.apply(_ref1, dom.childNodes);
      }
    }
    return this.section.replaceChildNodes(node);
  };

  return HtmlDecor;

})(require("./base"));

module.exports = HtmlDecor;
