// Generated by CoffeeScript 1.6.2
var Expression, base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

base = require("../../base/expression");

Expression = (function(_super) {
  __extends(Expression, _super);

  Expression.prototype._type = "string";

  function Expression(value) {
    this.value = value;
  }

  Expression.prototype.toString = function() {
    return "push('" + (this.value.replace(/\'/g, "\\'").replace(/\n/g, "\\n")) + "')";
  };

  return Expression;

})(base.Expression);

module.exports = Expression;
