// Generated by CoffeeScript 1.6.2
var BaseDecor;

BaseDecor = (function() {
  /*
  */
  function BaseDecor(node) {
    this.node = node;
  }

  /*
  */


  return BaseDecor;

})();

module.exports = BaseDecor;
