// Generated by CoffeeScript 1.6.2
var ClipBinding,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ClipBinding = (function(_super) {
  __extends(ClipBinding, _super);

  /*
  */


  function ClipBinding(clip) {
    this.clip = clip;
  }

  /*
  */


  ClipBinding.prototype.bind = function(context) {
    this.context = context;
    this.clip.reset(this.context);
    return this.clip.watch();
  };

  /*
  */


  ClipBinding.prototype.unbind = function() {
    return this.clip.unwatch();
  };

  return ClipBinding;

})(require("./base"));

module.exports = ClipBinding;
