// Generated by CoffeeScript 1.6.2
var DomFactory, Section, bindable;

bindable = require("bindable");

Section = (function() {
  /*
  */
  function Section() {}

  return Section;

})();

DomFactory = (function() {
  /*
  */
  function DomFactory(context) {
    this.context = context;
    this.internal = new bindable.Object();
  }

  /*
  */


  DomFactory.prototype.createElement = function(name) {
    return document.createElement(name);
  };

  /*
  */


  DomFactory.prototype.createTextNode = function(text) {
    return document.createTextNode(text);
  };

  /*
  */


  DomFactory.prototype.createFragment = function() {
    var child, frag, _i, _len;

    frag = document.createDocumentFragment();
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      child = arguments[_i];
      frag.appendChild(child);
    }
    return frag;
  };

  return DomFactory;

})();

module.exports = function(context) {
  return new DomFactory(context);
};
