// Generated by CoffeeScript 1.6.2
var ClickDecor, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ClickDecor = (function(_super) {
  __extends(ClickDecor, _super);

  function ClickDecor() {
    this._onClicked = __bind(this._onClicked, this);    _ref = ClickDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  ClickDecor.prototype.watch = false;

  /*
  */


  ClickDecor.prototype.bind = function() {
    ClickDecor.__super__.bind.call(this);
    return $(this.element).bind("click", this._onClicked);
  };

  /*
  */


  ClickDecor.prototype._onClicked = function(event) {
    return this.script.update();
  };

  return ClickDecor;

})(require("./dataBind"));

module.exports = ClickDecor;
