// Generated by CoffeeScript 1.6.2
var pcid;

pcid = 0;

exports.startBindingBlock = function(node, info) {
  return info.buffer.push("<!--spc:" + (node._pcid = ++pcid) + "-->");
};

exports.endBindingBlock = function(node, info) {
  return info.buffer.push("<!--epc:" + node._pcid + "-->");
};
