// Generated by CoffeeScript 1.6.2
/*
  scans for bindings
*/

var BindingScanner;

BindingScanner = (function() {
  function BindingScanner() {}

  /*
   Resursively scans for bindable DOM elements, and finds the associated binding
  */


  BindingScanner.prototype.bind = function(nodesById, currentElement) {
    var child, node, pcid, _i, _len, _ref, _results;

    if (currentElement.nodeName === "#comment" && currentElement.nodeValue.substr(0, 4) === "spc:") {
      pcid = currentElement.nodeValue.substr(4);
      if (!(node = nodesById[pcid])) {
        return;
      }
      node.bind(this._boundElements(pcid, currentElement.nextSibling, []));
    }
    _ref = currentElement.childNodes;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      _results.push(this.bind(nodesById, child));
    }
    return _results;
  };

  /*
   scans for all elements until the end binding block
  */


  BindingScanner.prototype._boundElements = function(pcid, currentElement, elements) {
    if (!currentElement || (currentElement.nodeName === "#comment" && currentElement.nodeValue === ("epc:" + pcid))) {
      return elements;
    } else {
      elements.push(currentElement);
      return this._boundElements(pcid, currentElement.nextSibling, elements);
    }
  };

  return BindingScanner;

})();
