// Generated by CoffeeScript 1.6.2
var BaseWriter;

BaseWriter = (function() {
  /*
  */
  function BaseWriter(loader) {
    this.loader = loader;
    this.nodeFactory = loader.nodeFactory;
    this.bindings = loader.bindings;
  }

  return BaseWriter;

})();

module.exports = BaseWriter;
