// Generated by CoffeeScript 1.6.2
(function() {
  var BaseWriter;

  BaseWriter = (function() {
    /*
    */
    function BaseWriter(template) {
      this.template = template;
      this.nodeFactory = template.application.nodeFactory;
      this.application = this.template.application;
      this.binders = template.binders;
    }

    /*
    */


    BaseWriter.prototype.write = function(script, contentFactory, childBlockFactory) {};

    return BaseWriter;

  })();

  module.exports = BaseWriter;

}).call(this);
