// Generated by CoffeeScript 1.6.2
(function() {
  var BaseWriter;

  BaseWriter = (function() {
    /*
    */
    function BaseWriter(loader) {
      this.loader = loader;
      this.nodeFactory = loader.application.nodeFactory;
      this.application = this.loader.application;
      this.bindings = loader.bindings;
      this.template = loader.template;
      this.bindingPaths = loader.bindingPaths;
    }

    /*
    */


    BaseWriter.prototype.write = function(script, contentFactory, childBlockFactory) {};

    return BaseWriter;

  })();

  module.exports = BaseWriter;

}).call(this);
