// Generated by CoffeeScript 1.6.2
var BlockWriter, loaf,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

loaf = require("loaf");

BlockWriter = (function() {
  /*
  */
  function BlockWriter(paper, nodeFactory) {
    this.paper = paper;
    this.nodeFactory = nodeFactory;
    this.write = __bind(this.write, this);
  }

  /*
  */


  BlockWriter.prototype.write = function(script, contentFactory, childBindings) {
    var section;

    section = loaf();
    return section.toFragment();
  };

  return BlockWriter;

})();

module.exports = BlockWriter;
