// Generated by CoffeeScript 1.6.2
var Fragment,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Fragment = (function(_super) {
  __extends(Fragment, _super);

  /*
  */


  function Fragment(children) {
    Fragment.__super__.constructor.call(this);
    this.addChild.apply(this, children);
  }

  return Fragment;

})(require("./base"));

module.exports = function(children) {
  return new Fragment(children);
};
