// Generated by CoffeeScript 1.7.0
(function() {
  var TextWriter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TextWriter = (function(_super) {
    __extends(TextWriter, _super);

    function TextWriter() {
      this.write = __bind(this.write, this);
      return TextWriter.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    TextWriter.prototype.write = function(text) {
      return this.nodeFactory.createTextNode(text);
    };

    return TextWriter;

  })(require("./base"));

  module.exports = TextWriter;

}).call(this);
