// Generated by CoffeeScript 1.6.2
var TextWriter,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

TextWriter = (function() {
  /*
  */
  function TextWriter(pape, nodeFactory) {
    this.pape = pape;
    this.nodeFactory = nodeFactory;
    this.write = __bind(this.write, this);
  }

  /*
  */


  TextWriter.prototype.write = function(text) {
    return this.nodeFactory.createTextNode(text);
  };

  return TextWriter;

})();

module.exports = TextWriter;
