// Generated by CoffeeScript 1.6.2
var Handler;

Handler = (function() {
  /*
  */
  function Handler(script, clip, element) {
    this.script = script;
    this.clip = clip;
    this.element = element;
  }

  /*
  */


  Handler.prototype.init = function() {
    if (this.watch !== false) {
      return this.script.watch();
    }
  };

  return Handler;

})();

module.exports = Handler;
