// Generated by CoffeeScript 1.6.2
var StyleDecor, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StyleDecor = (function(_super) {
  __extends(StyleDecor, _super);

  function StyleDecor() {
    this._updateStyle = __bind(this._updateStyle, this);    _ref = StyleDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  StyleDecor.prototype.bind = function() {
    StyleDecor.__super__.bind.call(this);
    this._currentStyles = {};
    this.$element = $(this.element);
    return this.clip.bind("style").to(this._updateStyle).now();
  };

  /*
  */


  StyleDecor.prototype._updateStyle = function(styles) {
    var hasNew, name, newStyles, style;

    newStyles = {};
    hasNew = false;
    for (name in styles) {
      style = styles[name];
      if (style !== this._currentStyles[name]) {
        newStyles[name] = this._currentStyles[name] = style;
        hasNew = true;
      }
    }
    if (hasNew) {
      return this.$element.css(newStyles);
    }
  };

  return StyleDecor;

})(require("./dataBind"));

module.exports = StyleDecor;
