// Generated by CoffeeScript 1.6.2
var NodeDecor,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

NodeDecor = (function() {
  /*
  */
  function NodeDecor(node) {
    this.node = node;
    this._onChange = __bind(this._onChange, this);
    this.script = node.clip.script(this.constructor.scriptName);
    this.clip = node.clip;
  }

  /*
  */


  NodeDecor.prototype.load = function(context, callback) {
    return callback();
  };

  /*
  */


  NodeDecor.prototype.bind = function() {
    return this.clip.bind(this.constructor.scriptName, this._onChange);
  };

  /*
  */


  NodeDecor.prototype._onChange = function(value) {};

  /*
  */


  NodeDecor.test = function(node) {
    return false;
  };

  return NodeDecor;

})();

module.exports = NodeDecor;
