// Generated by CoffeeScript 1.6.2
/*

{{#block:"blockContent"}}
  hello world!
{{/}}

{{html:blockContent}}
*/

var BlockDecor, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BlockDecor = (function(_super) {
  __extends(BlockDecor, _super);

  function BlockDecor() {
    _ref = BlockDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  BlockDecor.scriptName = "block";

  /*
  */


  BlockDecor.prototype.load = function(context, callback) {
    context.set(this.clip.get("block"), this.node.content);
    return callback();
  };

  return BlockDecor;

})(require("./base"));

module.exports = BlockDecor;
