// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    uppercase: function(value) {
      return String(value).toUpperCase();
    },
    lowercase: function(value) {
      return String(value).toLowerCase();
    },
    bothWays: function(value, y) {
      if (y == null) {
        y = true;
      }
      return this.options.bothWays = y;
    }
  };

}).call(this);
