// Generated by CoffeeScript 1.6.3
var Loader, Template, nofactor, tpl;

nofactor = require("nofactor");

Loader = require("./loader");

Template = (function() {
  /*
  */

  function Template(paper, application) {
    this.paper = paper;
    this.application = application;
  }

  /*
  */


  Template.prototype.bind = function(context) {
    return new Loader(this).load(context).bind();
  };

  return Template;

})();

Template.prototype.creator = module.exports = tpl = function(paperOrSrc, application) {
  var paper;
  if (!application) {
    application = {
      nodeFactory: nofactor["default"],
      $: typeof $ !== "undefined" && $ !== null
    };
  }
  if (typeof paperOrSrc === "string") {
    if (!tpl.compiler) {
      throw new Error("template must be a function");
    }
    paper = tpl.compiler.compile(paperOrSrc, {
      "eval": true
    });
  } else {
    paper = paperOrSrc;
  }
  return new Template(paper, application);
};
