// Generated by CoffeeScript 1.6.2
var Loader, Template, nofactor;

nofactor = require("nofactor");

Loader = require("./loader");

Template = (function() {
  /*
  */
  function Template(paper, nodeFactory) {
    this.paper = paper;
    this.nodeFactory = nodeFactory != null ? nodeFactory : nofactor["default"];
  }

  /*
  */


  Template.prototype.load = function(context) {
    return new Loader(this).load(context);
  };

  /*
  */


  Template.prototype.bind = function(context) {
    return this.load(context).bind();
  };

  return Template;

})();

module.exports = Template;
