// Generated by CoffeeScript 1.6.2
var Binding;

Binding = (function() {
  /*
  */
  function Binding(script, children) {
    this.script = script;
    this.children = children;
  }

  /*
  */


  Binding.prototype.write = function(writer, next) {};

  return Binding;

})();

module.exports = Binding;
