// Generated by CoffeeScript 1.6.2
var browser, cache, compile, fs;

browser = require("../../browser");

fs = require("fs");

cache = {};

compile = function(path) {
  var bindable, content, loader, tpl;

  content = fs.readFileSync(path, "utf8");
  tpl = browser.template(content);
  bindable = new browser.bindable.Object();
  bindable.set("this", bindable);
  bindable.set("path", path);
  loader = tpl.bind(bindable);
  return function(data) {
    bindable.reset(data);
    return loader.toString();
  };
};

module.exports = function(path, options, next) {
  var tpl;

  tpl = cache[path] || (cache[path] = compile(path));
  return next(null, tpl(options));
};
