// Generated by CoffeeScript 1.6.2
var NodeBindingFactory, decorClasses;

decorClasses = [];

NodeBindingFactory = (function() {
  function NodeBindingFactory() {}

  /*
  */


  NodeBindingFactory.prototype.getBindings = function(node) {
    var decor, decorClass, _i, _len, _results;

    decor = [];
    _results = [];
    for (_i = 0, _len = decorClasses.length; _i < _len; _i++) {
      decorClass = decorClasses[_i];
      if (decorClass.test(node)) {
        _results.push(decor.push(new decorClass));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return NodeBindingFactory;

})();
