// Generated by CoffeeScript 1.6.2
(function() {
  var Clip, paper;

  Clip = require("./clip");

  paper = require("./paper");

  module.exports = paper;

  if (typeof window !== "undefined") {
    window.paperclip = module.exports;
  }

}).call(this);
