// Generated by CoffeeScript 1.6.2
(function() {
  var Clip, Paper, Paperclip;

  Clip = require("./clip");

  Paper = require("./paper");

  Paperclip = (function() {
    /*
    */
    function Paperclip() {}

    /*
     attaches the context (data), to the element
    */


    Paperclip.prototype.attach = function(data, element) {
      var dom;

      dom = new Paper.DOM();
      return dom.attach(data, element);
    };

    return Paperclip;

  })();

  module.exports = function() {
    return new Paperclip();
  };

  module.exports.Clip = Clip;

  module.exports.Paper = Paper;

  module.exports.bindable = require("bindable");

  if (typeof window !== "undefined") {
    window.paperclip = module.exports;
  }

}).call(this);
