// Generated by CoffeeScript 1.7.0
(function() {
  var Clip, adapters, browser, fs, paper, translate;

  Clip = require("./clip");

  paper = require("./paper");

  browser = require("./browser");

  translate = require("./translate");

  adapters = require("./node/adapters");

  fs = require("fs");

  require("./node");

  module.exports = browser;

  module.exports.compile = translate.compile;

  module.exports.translator = translate;

  module.exports.adapters = adapters;

  paper.template.compiler = translate;

  require.extensions[".pc"] = function(module, filename) {
    return module.exports = translate.compile(fs.readFileSync(filename, "utf8"));
  };

}).call(this);
