// Generated by CoffeeScript 1.6.2
var ActionExpression, base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

base = require("../../base/expression");

ActionExpression = (function(_super) {
  __extends(ActionExpression, _super);

  ActionExpression.prototype._type = "action";

  function ActionExpression(name, options) {
    this.name = name;
    this.options = options;
    ActionExpression.__super__.constructor.call(this);
  }

  ActionExpression.prototype.references = function() {
    return this.options.references();
  };

  ActionExpression.prototype.toString = function() {
    var buffer;

    buffer = ["{"];
    buffer.push("name:'" + this.name + "', ");
    buffer.push("value:" + this.options.toString());
    buffer.push("}");
    return buffer.join("");
  };

  return ActionExpression;

})(base.Expression);

module.exports = ActionExpression;
