// Generated by CoffeeScript 1.6.2
(function() {
  var StringExpression, base;

  base = require("../../base/expression");

  StringExpression = (function() {
    StringExpression.prototype._type = "string";

    function StringExpression(value) {
      this.value = value;
    }

    StringExpression.prototype.toString = function() {
      return "'" + (this.value.replace("\'", "\\'").replace("\n", "\\n")) + "'";
    };

    return StringExpression;

  })();

  module.exports = StringExpression;

}).call(this);
