// Generated by CoffeeScript 1.6.2
var ComponentDecor, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ComponentDecor = (function(_super) {
  __extends(ComponentDecor, _super);

  function ComponentDecor() {
    _ref = ComponentDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  ComponentDecor.prototype.load = function(context, callback) {
    var child, onContentLoad, tpl, tplName,
      _this = this;

    tplName = "template." + (this.clip.get("component.name") || this.clip.get("component"));
    tpl = context.internal.get(tplName);
    if (!tpl) {
      return callback();
    }
    child = context.child().detachBuffer();
    onContentLoad = function() {
      child.set("content", child.buffer.join(""));
      child.attachBuffer();
      return tpl.write(child, callback);
    };
    if (this.node.content) {
      return this.node.content.load(child, onContentLoad);
    } else {
      return onContentLoad();
    }
  };

  return ComponentDecor;

})(require("./base"));

module.exports = ComponentDecor;
