// Generated by CoffeeScript 1.6.2
var HtmlDecor, type, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

type = require("type-component");

HtmlDecor = (function(_super) {
  __extends(HtmlDecor, _super);

  function HtmlDecor() {
    _ref = HtmlDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  HtmlDecor.prototype.load = function(context) {
    var html;

    this.context = context;
    html = this.clip.get("html");
    if (html == null) {
      return;
    }
    return this._onChange(html);
  };

  /*
  */


  HtmlDecor.prototype.bind = function() {
    var _ref1;

    HtmlDecor.__super__.bind.call(this);
    return (_ref1 = this.child) != null ? _ref1.bind() : void 0;
  };

  /*
  */


  HtmlDecor.prototype.unbind = function() {
    var _ref1;

    HtmlDecor.__super__.unbind.call(this);
    return (_ref1 = this.child) != null ? _ref1.unbind() : void 0;
  };

  /*
  */


  HtmlDecor.prototype._onChange = function(value) {
    var node;

    if (!value) {
      return this.block.removeAll();
    }
    if (value.__isWriter) {
      node = value.node;
    } else if (value.__isNode) {
      node = value;
    } else {
      node = this.context.nodeFactory.parseHtml(String(value));
    }
    return this.block.replaceAll(node);
  };

  return HtmlDecor;

})(require("./base"));

module.exports = HtmlDecor;
