// Generated by CoffeeScript 1.6.2
var IncludeDecor,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

IncludeDecor = (function(_super) {
  __extends(IncludeDecor, _super);

  /*
  */


  function IncludeDecor() {}

  return IncludeDecor;

})(require("./base"));

module.exports = IncludeDecor;
