// Generated by CoffeeScript 1.6.2
var TemplateDecor, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TemplateDecor = (function(_super) {
  __extends(TemplateDecor, _super);

  function TemplateDecor() {
    _ref = TemplateDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  TemplateDecor.prototype.load = function(stream) {
    return stream.internal.set("template." + (this.clip.get("template.name") || this.clip.get("template")), this);
  };

  return TemplateDecor;

})(require("./base"));

module.exports = TemplateDecor;
