// Generated by CoffeeScript 1.6.2
var BaseDataBindHandler,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseDataBindHandler = (function(_super) {
  __extends(BaseDataBindHandler, _super);

  /*
  */


  function BaseDataBindHandler(node, clip, name) {
    this.node = node;
    this.clip = clip;
    this.name = name;
    BaseDataBindHandler.__super__.constructor.call(this, this.clip, this.name);
  }

  return BaseDataBindHandler;

})(require("../../../../base/script"));

module.exports = BaseDataBindHandler;
