// Generated by CoffeeScript 1.7.0
(function() {
  var ChangeAttrBinding,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ChangeAttrBinding = (function(_super) {
    __extends(ChangeAttrBinding, _super);

    function ChangeAttrBinding() {
      this._update2 = __bind(this._update2, this);
      return ChangeAttrBinding.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    ChangeAttrBinding.events = "keydown change input mousedown mouseup click";


    /*
     */

    ChangeAttrBinding.prototype.preventDefault = false;


    /*
     */

    ChangeAttrBinding.prototype.event = ChangeAttrBinding.events;


    /*
     */

    ChangeAttrBinding.prototype._update = function(event) {
      clearTimeout(this._changeTimeout);
      return this._changeTimeout = setTimeout(this._update2, 5);
    };


    /*
     */

    ChangeAttrBinding.prototype._update2 = function() {
      return this.script.update();
    };

    return ChangeAttrBinding;

  })(require("./event"));

  module.exports = ChangeAttrBinding;

}).call(this);
