// Generated by CoffeeScript 1.7.0
(function() {
  var DeleteAttrBinding,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DeleteAttrBinding = (function(_super) {
    __extends(DeleteAttrBinding, _super);

    function DeleteAttrBinding() {
      this._onEvent = __bind(this._onEvent, this);
      return DeleteAttrBinding.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    DeleteAttrBinding.prototype.event = "keydown";


    /*
     */

    DeleteAttrBinding.prototype.preventDefault = true;


    /*
     */

    DeleteAttrBinding.prototype._onEvent = function(event) {
      var _ref;
      if ((_ref = event.keyCode) !== 8) {
        return;
      }
      return DeleteAttrBinding.__super__._onEvent.call(this, event);
    };

    return DeleteAttrBinding;

  })(require("./event"));

  module.exports = DeleteAttrBinding;

}).call(this);
