// Generated by CoffeeScript 1.7.0
(function() {
  var EnableAttrBinding,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EnableAttrBinding = (function(_super) {
    __extends(EnableAttrBinding, _super);

    function EnableAttrBinding() {
      return EnableAttrBinding.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    EnableAttrBinding.prototype._onChange = function(value) {
      if (value) {
        return this.node.removeAttribute("disabled");
      } else {
        return this.node.setAttribute("disabled", "disabled");
      }
    };

    return EnableAttrBinding;

  })(require("./base"));

  module.exports = EnableAttrBinding;

}).call(this);
