// Generated by CoffeeScript 1.7.0
(function() {
  var EnterAttrBinding,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EnterAttrBinding = (function(_super) {
    __extends(EnterAttrBinding, _super);

    function EnterAttrBinding() {
      this._onEvent = __bind(this._onEvent, this);
      return EnterAttrBinding.__super__.constructor.apply(this, arguments);
    }


    /*
     */

    EnterAttrBinding.prototype.event = "keydown";


    /*
     */

    EnterAttrBinding.prototype.preventDefault = true;


    /*
     */

    EnterAttrBinding.prototype._onEvent = function(event) {
      if (event.keyCode !== 13) {
        return;
      }
      return EnterAttrBinding.__super__._onEvent.call(this, event);
    };

    return EnterAttrBinding;

  })(require("./event"));

  module.exports = EnterAttrBinding;

}).call(this);
