// Generated by CoffeeScript 1.6.2
var StyleDecor, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StyleDecor = (function(_super) {
  __extends(StyleDecor, _super);

  function StyleDecor() {
    _ref = StyleDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  StyleDecor.prototype.bind = function() {
    this._currentStyles = {};
    return StyleDecor.__super__.bind.call(this);
  };

  /*
  */


  StyleDecor.prototype._onChange = function(styles) {
    var key, name, newStyles, rmStyle, style, _results;

    newStyles = {};
    rmStyle = {};
    for (name in styles) {
      style = styles[name];
      if (style !== this._currentStyles[name]) {
        newStyles[name] = this._currentStyles[name] = style || "";
      }
    }
    if (typeof window === "undefined") {
      _results = [];
      for (key in newStyles) {
        _results.push(this.node.style[key] = newStyles[key]);
      }
      return _results;
    } else {
      return $(this.node).css(newStyles);
    }
  };

  return StyleDecor;

})(require("./base"));

module.exports = StyleDecor;
