// Generated by CoffeeScript 1.6.2
var BaseAttrBinding,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseAttrBinding = (function(_super) {
  __extends(BaseAttrBinding, _super);

  /*
  */


  function BaseAttrBinding(options) {
    BaseAttrBinding.__super__.constructor.call(this, options);
  }

  return BaseAttrBinding;

})(require("../../base"));

module.exports = BaseAttrBinding;
