// Generated by CoffeeScript 1.6.2
(function() {
  var BaseExpression;

  BaseExpression = (function() {
    /*
    */
    function BaseExpression() {}

    return BaseExpression;

  })();

  module.exports = BaseExpression;

}).call(this);
