// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionExpression, Evaluator;

  Evaluator = (function() {
    function Evaluator(expr, context) {
      this.expr = expr;
      this.context = context;
      this.items = this.expr.items.map(function(item) {
        return item.evaluate(context);
      });
    }

    Evaluator.prototype.toString = function() {
      return this.items.map(function(item) {
        return item.toString();
      }).join(" ");
    };

    return Evaluator;

  })();

  CollectionExpression = (function() {
    CollectionExpression.prototype._type = "collection";

    /*
    */


    function CollectionExpression(items) {
      this.items = items;
    }

    /*
    */


    CollectionExpression.prototype.evaluate = function(context) {
      return new Evaluator(this, context);
    };

    return CollectionExpression;

  })();

  module.exports = CollectionExpression;

  module.exports.Evaluator = Evaluator;

}).call(this);
