// Generated by CoffeeScript 1.6.2
(function() {
  var FnExpression;

  FnExpression = (function() {
    /*
    */
    function FnExpression(name, params) {
      this.name = name;
      this.params = params;
    }

    return FnExpression;

  })();

  module.exports = FnExpression;

}).call(this);
