// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, FnExpression;

  Evaluator = (function() {
    /*
    */
    function Evaluator(expr, context) {
      this.expr = expr;
      this.context = context;
      this.name = expr.name;
      this.params = this.expr.params.evaluate();
    }

    return Evaluator;

  })();

  FnExpression = (function() {
    FnExpression.prototype._type = "fn";

    /*
    */


    function FnExpression(name, params) {
      this.name = name;
      this.params = params;
    }

    /*
    */


    FnExpression.prototype.evaluate = function(context) {
      return new Evaluator(this, context);
    };

    return FnExpression;

  })();

  module.exports = FnExpression;

}).call(this);
