// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, JSExpression;

  Evaluator = (function() {
    /*
    */
    function Evaluator(expr) {
      this.expr = expr;
    }

    Evaluator.prototype.init = function() {};

    /*
    */


    Evaluator.prototype.toString = function() {
      return this.expr.value;
    };

    return Evaluator;

  })();

  JSExpression = (function() {
    JSExpression.prototype._type = "js";

    /*
    */


    function JSExpression(value) {
      this.value = value;
    }

    /*
    */


    JSExpression.prototype.evaluate = function() {
      return new Evaluator(this);
    };

    return JSExpression;

  })();

  module.exports = JSExpression;

}).call(this);
