// Generated by CoffeeScript 1.6.2
(function() {
  var RefExpression, base;

  base = require("./base");

  RefExpression = (function() {
    RefExpression.prototype._type = "ref";

    function RefExpression(name) {
      this.name = name;
    }

    RefExpression.prototype.toString = function() {
      return this.name;
    };

    RefExpression.prototype.references = function() {
      return [];
    };

    return RefExpression;

  })();

  module.exports = RefExpression;

}).call(this);
