// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, RefPathExpression;

  Evaluator = (function() {
    function Evaluator(expr, context) {
      this.expr = expr;
      this.context = context;
    }

    return Evaluator;

  })();

  RefPathExpression = (function() {
    /*
    */
    function RefPathExpression(path) {
      this.path = path;
    }

    RefPathExpression.prototype["eval"] = function(context) {
      return new Evaluator(this, context);
    };

    return RefPathExpression;

  })();

  module.exports = RefPathExpression;

}).call(this);
