// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, ScriptExpression, base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  base = require("./base");

  Evaluator = (function(_super) {
    __extends(Evaluator, _super);

    function Evaluator() {
      Evaluator.__super__.constructor.apply(this, arguments);
      this.references = this.linkChild(this.expr.references.evaluate(this.clip));
      this.modifiers = this.linkChild(this.expr.modifiers.evaluate(this.clip));
    }

    /*
    */


    Evaluator.prototype.toString = function() {
      return this.references.toString();
    };

    return Evaluator;

  })(base.Evaluator);

  ScriptExpression = (function() {
    ScriptExpression.prototype._type = "script";

    /*
    */


    function ScriptExpression(references, modifiers) {
      this.references = references;
      this.modifiers = modifiers;
    }

    /*
    */


    ScriptExpression.prototype.evaluate = function(context) {
      return new Evaluator(this, context);
    };

    return ScriptExpression;

  })();

  module.exports = ScriptExpression;

}).call(this);
