// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, ScriptExpression, base, events,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  base = require("./base");

  events = require("events");

  Evaluator = (function(_super) {
    __extends(Evaluator, _super);

    function Evaluator() {
      Evaluator.__super__.constructor.apply(this, arguments);
      this._em = new events.EventEmitter();
      this.expressions = this.linkChild(this.expr.expressions.evaluate(this.clip));
      this.modifiers = this.linkChild(this.expr.modifiers.evaluate(this.clip));
    }

    /*
    */


    Evaluator.prototype.init = function() {
      this._compile();
      return Evaluator.__super__.init.call(this);
    };

    /*
    */


    Evaluator.prototype.bind = function(to) {
      this._em.on("change", to);
      if (this._currentValue !== void 0) {
        return to(this._currentValue);
      }
    };

    /*
    */


    Evaluator.prototype.toString = function() {
      return this.expressions.toString();
    };

    Evaluator.prototype._compile = function() {
      var fn,
        _this = this;

      fn = eval("(function(){ return " + (this.expressions.toString()) + " })");
      return this._evalFn = function() {
        return fn.call(_this.clip);
      };
    };

    Evaluator.prototype._change = function() {
      Evaluator.__super__._change.call(this);
      return this._em.emit("change", this._currentValue = this._evalFn());
    };

    return Evaluator;

  })(base.Evaluator);

  ScriptExpression = (function() {
    ScriptExpression.prototype._type = "script";

    /*
    */


    function ScriptExpression(expressions, modifiers) {
      this.expressions = expressions;
      this.modifiers = modifiers;
    }

    /*
    */


    ScriptExpression.prototype.evaluate = function(context) {
      return new Evaluator(this, context);
    };

    return ScriptExpression;

  })();

  module.exports = ScriptExpression;

}).call(this);
