// Generated by CoffeeScript 1.6.2
var DOM, DecororFactory;

DecororFactory = require("./decor");

DOM = (function() {
  /*
  */
  function DOM() {
    this._decorFactory = new DecororFactory();
  }

  /*
  */


  DOM.prototype.attach = function(context, element) {
    var _this = this;

    return this._traverse(this._element(element), function(element) {
      var decor, decors, traverse, _i, _len;

      decors = _this._decorFactory.attach(context, element);
      if (decors) {
        for (_i = 0, _len = decors.length; _i < _len; _i++) {
          decor = decors[_i];
          decor.dom = _this;
          decor.init();
          traverse = decor !== false;
        }
        if (traverse === false) {
          return false;
        }
      }
    });
  };

  /*
  */


  DOM.prototype._traverse = function(element, callback) {
    var child, traverse, _i, _len, _ref, _results;

    if (element.nodeName === "#comment") {
      return;
    }
    traverse = callback(element);
    if (traverse === false) {
      return;
    }
    _ref = element.childNodes;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      if (this._traverse(child, callback) === false) {
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  /*
  */


  DOM.prototype._element = function(element) {
    return element[0] || element;
  };

  return DOM;

})();

module.exports = DOM;
