// Generated by CoffeeScript 1.6.2
var CheckedDecor, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CheckedDecor = (function(_super) {
  __extends(CheckedDecor, _super);

  function CheckedDecor() {
    this._show = __bind(this._show, this);    _ref = CheckedDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  CheckedDecor.prototype.bind = function() {
    CheckedDecor.__super__.bind.call(this);
    return this.clip.bind("checked").to(this._show);
  };

  /*
  */


  CheckedDecor.prototype._show = function(value) {
    return this.element.checked = value;
  };

  return CheckedDecor;

})(require("./dataBind"));

module.exports = CheckedDecor;
