// Generated by CoffeeScript 1.6.2
var EnterDecor, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EnterDecor = (function(_super) {
  __extends(EnterDecor, _super);

  function EnterDecor() {
    this._onKeyUp = __bind(this._onKeyUp, this);    _ref = EnterDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  EnterDecor.prototype.watch = false;

  /*
  */


  EnterDecor.prototype.bind = function() {
    EnterDecor.__super__.bind.call(this);
    return $(this.element).bind("keyup", this._onKeyUp);
  };

  /*
  */


  EnterDecor.prototype._onKeyUp = function(event) {
    if (event.keyCode !== 13) {
      return;
    }
    return this.script.update();
  };

  return EnterDecor;

})(require("./dataBind"));

module.exports = EnterDecor;
