// Generated by CoffeeScript 1.6.2
var ShowDecor, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ShowDecor = (function(_super) {
  __extends(ShowDecor, _super);

  function ShowDecor() {
    this._show = __bind(this._show, this);    _ref = ShowDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  ShowDecor.prototype.bind = function() {
    ShowDecor.__super__.bind.call(this);
    this.$element = $(this.element);
    this.clip.bind("show").to(this._show).now();
    return this._show(this.clip.get("show"));
  };

  /*
  */


  ShowDecor.prototype._show = function(value) {
    return this.$element.css({
      "display": value ? "block" : "none"
    });
  };

  return ShowDecor;

})(require("./dataBind"));

module.exports = ShowDecor;
