// Generated by CoffeeScript 1.6.2
var ValueDecor, _, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require("underscore");

ValueDecor = (function(_super) {
  __extends(ValueDecor, _super);

  function ValueDecor() {
    this._isInput = __bind(this._isInput, this);
    this._elementValue = __bind(this._elementValue, this);
    this._onChange = __bind(this._onChange, this);
    this._onElementChange = __bind(this._onElementChange, this);    _ref = ValueDecor.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  ValueDecor.prototype.bind = function() {
    ValueDecor.__super__.bind.call(this);
    $(this.element).bind("keydown change input", _.debounce(this._onElementChange, 1));
    return this._onChange(this.clip.get("value"));
  };

  /*
  */


  ValueDecor.prototype._onElementChange = function(event) {
    var _this = this;

    return setTimeout((function() {
      var ref, value, _i, _len, _ref1, _results;

      value = _this._elementValue();
      if (_this.clip.get("bothWays")) {
        _ref1 = _this.refs;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          ref = _ref1[_i];
          _results.push(_this.context.set(ref, value));
        }
        return _results;
      }
    }), 5);
  };

  /*
  */


  ValueDecor.prototype._onChange = function(value) {
    return this._elementValue(value);
  };

  /*
  */


  ValueDecor.prototype._elementValue = function(value) {
    var isInput;

    isInput = this._isInput();
    if (!arguments.length) {
      if (isInput) {
        return this.element.value;
      } else {
        return this.element.innerHTML;
      }
    }
    this.currentValue = value;
    if (isInput) {
      return this.element.value = value;
    } else {
      return this.element.innerHTML = value;
    }
  };

  /*
  */


  ValueDecor.prototype._isInput = function() {
    return this.element.hasOwnProperty("value");
  };

  return ValueDecor;

})(require("./dataBind"));

module.exports = ValueDecor;
