// Generated by CoffeeScript 1.6.2
var AttrDataBinding, BindingCollection, Clip, dataBindingClasses,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Clip = require("../../../../../clip");

BindingCollection = require("../../../collection");

dataBindingClasses = {
  show: require("./handlers/show"),
  css: require("./handlers/css"),
  style: require("./handlers/style"),
  disable: require("./handlers/disable")
};

AttrDataBinding = (function(_super) {
  __extends(AttrDataBinding, _super);

  /*
  */


  AttrDataBinding.prototype.type = "attr";

  /*
  */


  function AttrDataBinding(options) {
    var bc, scriptName, _i, _len, _ref;

    AttrDataBinding.__super__.constructor.call(this, options);
    this.clip = new Clip({
      scripts: options.value[0],
      watch: false
    });
    this._bindings = new BindingCollection();
    _ref = this.clip.scripts.names;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      scriptName = _ref[_i];
      if (!(bc = dataBindingClasses[scriptName])) {
        continue;
      }
      this._bindings.push(new bc(this.node, this.clip, scriptName));
    }
  }

  /*
  */


  AttrDataBinding.prototype.bind = function(context) {
    this.context = context;
    this.clip.watch().reset(this.context);
    return this._bindings.bind();
  };

  /*
  */


  AttrDataBinding.prototype.unbind = function() {
    this.clip.unwatch();
    return this._bindings.unbind();
  };

  return AttrDataBinding;

})(require("../base"));

module.exports = AttrDataBinding;

module.exports.register = function(name, dataBindClass) {
  return dataBindingClasses[name] = dataBindClass;
};
