// Generated by CoffeeScript 1.6.2
var DecorCollection, Factory, blockDecorators;

DecorCollection = require("./collection");

blockDecorators = {
  html: require("./block/html"),
  block: require("./block/block"),
  when: require("./block/when"),
  "with": require("./block/with"),
  each: require("./block/each"),
  value: require("./block/value"),
  template: require("./block/template"),
  component: require("./block/template")
};

Factory = (function() {
  function Factory() {}

  /*
  */


  Factory.prototype.getDecor = function(node) {
    var bd, decor, scriptName, _i, _len, _ref;

    decor = new DecorCollection();
    _ref = node.clip.scripts.names;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      scriptName = _ref[_i];
      if (bd = blockDecorators[scriptName]) {
        decor.push(new bd(node, scriptName));
      }
    }
    return decor;
  };

  return Factory;

})();

module.exports = new Factory();
