// Generated by CoffeeScript 1.6.2
var Collection, async;

async = require("async");

Collection = (function() {
  /*
  */
  function Collection() {
    this._items = [];
  }

  /*
  */


  Collection.prototype.push = function(item) {
    return this._items.push(item);
  };

  /*
  */


  Collection.prototype.load = function(context, callback) {
    var _ref;

    if ((_ref = this.clip) != null) {
      _ref.reset(context, false);
    }
    return async.eachSeries(this._items, (function(decor, next) {
      return decor.load(context, next);
    }), callback);
  };

  /*
  */


  Collection.prototype.bind = function() {
    var decor, _i, _len, _ref, _results;

    if (this._bound) {
      return;
    }
    this._bound = true;
    _ref = this._items;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      decor = _ref[_i];
      _results.push(decor.bind());
    }
    return _results;
  };

  return Collection;

})();

module.exports = Collection;
